name: Continuous Integration
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:
env:
  IMAGE: ${{ vars.REGISTRY}}/${{ vars.PROJECT }}

jobs:
  Validation:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          ref: deploy

      - name: Setup environment
        uses: astral-sh/setup-uv@v7.2.0
        with:
          version: 0.9.22
          python-version: 3.12

      - name: Linting and testing
        run: |
          uv run ruff check .
          uv run pytest

  Packaging:
    needs: Validation
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          ref: deploy

      - name: Compute image tag
        id: meta
        run: |
          SHA="${{ github.sha }}"
          echo "tag=${SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ steps.meta.outputs.tag }}

  Deployment:
    needs: Packaging
    uses: hanatole/deployer/.github/workflows/cd.yml@main
    with:
      project_directory: "/srv/todo"
      traefik_rule: "Host(`api.ah.imc.chillo.fr`)"
      network_name: traefiknetwork
      service_name: "todo-backend"
      service_port: 8000
      fqn_docker_image: ${{env.IMAGE}}
      docker_image_tag: ${{ needs.Packaging.outputs.tag }}
      tier: "backend"
    secrets: inherit