name: Continuous Integration
on:
  push:
    branches: [ deploy ]

jobs:
  Validation:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          ref: deploy

      - name: Setup environment
        uses: astral-sh/setup-uv@v7.2.0
        with:
          version: 0.9.22
          python-version: 3.12

      - name: Linting and testing
        run: |
          uv run ruff check .
          uv run pytest
