name: Continuous Integration
on: push

jobs:
  validation:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: astral-sh/setup-uv@v7.2.0
        with:
          version: 0.9.22
          python-version: 3.12

      - name: Linting and testing
        run: |
          uv run ruff check .
          uv run pytest

      - name: Sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        with:
          ProjectBaseDir: .
          args: >
            '-Dsonar.projectName=Fastapi Todo'
            -Dsonar.projectKey=fastapi-todo
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests/
            -Dsonar.python.xunit.reportPath=reports/junit.xml
            -Dsonar.verbose=true
            -Dsonar.python.version=3.12
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
